# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{viewaide}
  s.version = "0.3.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Joshua Clayton"]
  s.date = %q{2010-01-09}
  s.description = %q{Making your views easier}
  s.email = %q{joshua.clayton@gmail.com}
  s.extra_rdoc_files = [
    "README.textile"
  ]
  s.files = [
    ".gitignore",
     "MIT-LICENSE",
     "Manifest",
     "README.textile",
     "Rakefile",
     "VERSION",
     "lib/viewaide.rb",
     "lib/viewaide/helpers.rb",
     "lib/viewaide/helpers/date_helper.rb",
     "lib/viewaide/helpers/form_helper.rb",
     "lib/viewaide/helpers/grid_helper.rb",
     "lib/viewaide/helpers/jquery_helper.rb",
     "lib/viewaide/helpers/link_helper.rb",
     "lib/viewaide/helpers/message_helper.rb",
     "lib/viewaide/helpers/navigation_helper.rb",
     "lib/viewaide/helpers/rjs_helper.rb",
     "lib/viewaide/helpers/structure_helper.rb",
     "lib/viewaide/helpers/table_helper.rb",
     "lib/viewaide/rails_partial_caching.rb",
     "rails/init.rb",
     "tasks/viewaide_tasks.rake",
     "test/date_helper_test.rb",
     "test/form_helper_test.rb",
     "test/grid_helper_test.rb",
     "test/jquery_helper_test.rb",
     "test/link_helper_test.rb",
     "test/message_helper_test.rb",
     "test/navigation_helper_test.rb",
     "test/rjs_helper_test.rb",
     "test/structure_helper_test.rb",
     "test/table_helper_test.rb",
     "test/test_helper.rb",
     "viewaide.gemspec"
  ]
  s.homepage = %q{http://github.com/joshuaclayton/viewaide}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Making your views easier}
  s.test_files = [
    "test/date_helper_test.rb",
     "test/form_helper_test.rb",
     "test/grid_helper_test.rb",
     "test/jquery_helper_test.rb",
     "test/link_helper_test.rb",
     "test/message_helper_test.rb",
     "test/navigation_helper_test.rb",
     "test/rjs_helper_test.rb",
     "test/structure_helper_test.rb",
     "test/table_helper_test.rb",
     "test/test_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<actionpack>, [">= 2.1.0"])
      s.add_runtime_dependency(%q<activesupport>, [">= 2.1.0"])
      s.add_runtime_dependency(%q<hpricot>, [">= 0.8.1"])
    else
      s.add_dependency(%q<actionpack>, [">= 2.1.0"])
      s.add_dependency(%q<activesupport>, [">= 2.1.0"])
      s.add_dependency(%q<hpricot>, [">= 0.8.1"])
    end
  else
    s.add_dependency(%q<actionpack>, [">= 2.1.0"])
    s.add_dependency(%q<activesupport>, [">= 2.1.0"])
    s.add_dependency(%q<hpricot>, [">= 0.8.1"])
  end
end

